### ISSUE TITLE
Basic Analytics

### ISSUE THREAD

**Issue by sielay** [getlackey/lackey-cms#43]
# Basic Analytics

## Type

 * Feature Request

### Metrics

 * Most active users (A)
 * Most popular content (B)
 * Most downloaded media (C)
 * Most performed click (D)

### Definitions

 * (A) user that had most of session during a day - new session is page impression after at lest 1h inactivity
 * (B) most popular content is one having biggest number of impressions in a day

### Tasks

- [x] define metric table
- [x] create generic metric collector with programatic API and REST endpoint
- [x] ensure session record store last impression
- [x] connect metric `A` to session handler - `incremental user / day`
- [x] collect page impression (B) - `incremental page / day`
- [x] extend media to allow proxing download via metric call (C)
- [x] add metric proxing to dust helper `{@media}` (C)
- [x] create frontend lib to log click events `data-analytics="click" data-analytics-id="XYZ"`
- [x] build table preview for analytics data - predefined view for each metric
- [x] build chart display for analytics data - predefined view for each metric
- [x] add XLSX export for tabular data

**Comment by sielay** [comment]
Released with #68 0.9.0-alpha
